In [5]:
import pandas as pd

df = pd.read_csv('liquor licenses active.csv', low_memory=False)
df.columns = df.columns.str.lower().str.replace(' ', '')

In [2]:
relevant = [
    'Night Club',
    'Cabaret',
    'Bar',
    'Tavern Miscellaneous',
    'Summer - Tavern Miscellaneous',
    'Additional Bar',
    'Additional Bar-Seasonal',
    'Public Dance Hall',
    'Concert Hall',
    'Club',
    'Summer Club',
    'Winter Club',
    'Restaurant',          # optional - depends if you want restaurant-bars
    'Catering Establishment',  # optional
]

In [6]:
# Filter to NYC only
nyc_counties = ['New York', 'Kings', 'Queens', 'Bronx', 'Richmond']
df = df[df['premisescounty'].isin(nyc_counties)]

# Filter to relevant venue types
df = df[df['description'].isin(relevant)]

# Drop rows missing critical info
df = df.dropna(subset=['actualaddressofpremises', 'city', 'statename'])

print(df.shape)
df.head()

(10982, 20)

,licensepermitid,premisescounty,type,class,description,legalname,dba,actualaddressofpremises,additionaladdressinformation,city,statename,zipcode,originalissuedate,lastissuedate,effectivedate,expirationdate,parentlicenseid,legacyserialnumber,akaaddress,georeference
63,0240-22-100853,Queens,1,0240,Restaurant,EL FOGON REST INC,NaN,1701 PALMETTO ST,NaN,RIDGEWOOD,New York,11385,01/28/2026,01/28/2026,02/01/2026,01/31/2028,NaN,1274758.0,NaN,POINT (-73.90473 40.70571)
64,0240-22-101032,New York,1,0240,Restaurant,ATOBOY LLC,NaN,43 E 28TH ST,NaN,NEW YORK,New York,10016,06/28/2024,06/28/2024,07/01/2024,06/30/2026,NaN,1295009.0,NaN,POINT (-73.98462 40.74356)
65,0240-23-139971,Queens,1,0240,Restaurant,SUSHI ME INC,SUSHI ME,14-18 150TH ST,NaN,WHITESTONE,New York,11357,06/03/2025,06/03/2025,07/01/2025,06/30/2027,NaN,1334896.0,NaN,POINT (-73.81389 40.78807)
66,0240-23-140239,Kings,1,0240,Restaurant,BENDOM BROOKLYN INC,BIG TINY,244 SMITH ST,NaN,BROOKLYN,New York,11231,04/28/2025,04/28/2025,06/01/2025,05/31/2027,NaN,1300517.0,NaN,POINT (-73.99269 40.68341)
67,0240-23-140773,New York,1,0240,Restaurant,AKAMI INC,NaN,1771 1ST AVE,NaN,NEW YORK,New York,10128,02/13/2025,02/13/2025,03/01/2025,02/28/2027,NaN,1282132.0,NaN,POINT (-73.94679 40.7804)

In [7]:
# Keep only useful columns
df = df[[
    'licensepermitid',
    'premisescounty',
    'description',
    'legalname',
    'dba',
    'actualaddressofpremises',
    'city',
    'statename',
    'zipcode',
    'originalissuedate',
    'expirationdate',
    'georeference'
]]

print(df.shape)
df.head()

(10982, 12)

,licensepermitid,premisescounty,description,legalname,dba,actualaddressofpremises,city,statename,zipcode,originalissuedate,expirationdate,georeference
63,0240-22-100853,Queens,Restaurant,EL FOGON REST INC,NaN,1701 PALMETTO ST,RIDGEWOOD,New York,11385,01/28/2026,01/31/2028,POINT (-73.90473 40.70571)
64,0240-22-101032,New York,Restaurant,ATOBOY LLC,NaN,43 E 28TH ST,NEW YORK,New York,10016,06/28/2024,06/30/2026,POINT (-73.98462 40.74356)
65,0240-23-139971,Queens,Restaurant,SUSHI ME INC,SUSHI ME,14-18 150TH ST,WHITESTONE,New York,11357,06/03/2025,06/30/2027,POINT (-73.81389 40.78807)
66,0240-23-140239,Kings,Restaurant,BENDOM BROOKLYN INC,BIG TINY,244 SMITH ST,BROOKLYN,New York,11231,04/28/2025,05/31/2027,POINT (-73.99269 40.68341)
67,0240-23-140773,New York,Restaurant,AKAMI INC,NaN,1771 1ST AVE,NEW YORK,New York,10128,02/13/2025,02/28/2027,POINT (-73.94679 40.7804)

In [8]:
df.to_csv('cleaned_venues.csv', index=False) 
print("Saved!")

Saved!

In [9]:
import pandas as pd

subway = pd.read_csv('MTA_Subway_Entrances_and_Exits__2024_20260320.csv')

# Check shape and nulls
print(subway.shape)
subway.isnull().sum()

(2120, 15)

Division                    0
Line                        0
Borough                     0
Stop Name                   0
Complex ID                  0
Constituent Station Name    0
Station ID                  0
GTFS Stop ID                0
Daytime Routes              0
Entrance Type               0
Entry Allowed               0
Exit Allowed                0
Entrance Latitude           0
Entrance Longitude          0
entrance_georeference       0
dtype: int64

In [10]:
# Keep only useful columns
subway = subway[[
    'Borough',
    'Stop Name',
    'Daytime Routes',
    'Entrance Type',
    'Entry Allowed',
    'Entrance Latitude',
    'Entrance Longitude'
]]

# Filter to entry-allowed only (no exit-only entrances)
subway = subway[subway['Entry Allowed'] == 'YES']

# Reset index
subway = subway.reset_index(drop=True)

print(subway.shape)
subway.head()

(2072, 7)

,Borough,Stop Name,Daytime Routes,Entrance Type,Entry Allowed,Entrance Latitude,Entrance Longitude
0,B,Atlantic Av-Barclays Ctr,2 3 4 5 B D N Q R,Stair,YES,40.683905,-73.978879
1,B,Atlantic Av-Barclays Ctr,2 3 4 5 B D N Q R,Elevator,YES,40.683805,-73.978487
2,B,Atlantic Av-Barclays Ctr,2 3 4 5 B D N Q R,Stair,YES,40.683928,-73.978412
3,B,Union St,R,Stair,YES,40.677154,-73.983430
4,B,Union St,R,Stair,YES,40.677296,-73.983336

In [11]:
subway.to_csv('cleaned_subway.csv', index=False)
print("Saved!")

Saved!

In [2]:
import pandas as pd

complaints = pd.read_csv('NYPD_Complaint_Data_Current_(Year_To_Date)_20260324.csv', low_memory=False)

# Normalize column names
complaints.columns = complaints.columns.str.lower().str.replace(' ', '')

print(complaints.shape)
print(complaints.columns.tolist())
complaints.head()

(186586, 36)
['cmplnt_num', 'addr_pct_cd', 'boro_nm', 'cmplnt_fr_dt', 'cmplnt_fr_tm', 'cmplnt_to_dt', 'cmplnt_to_tm', 'crm_atpt_cptd_cd', 'hadevelopt', 'housing_psa', 'jurisdiction_code', 'juris_desc', 'ky_cd', 'law_cat_cd', 'loc_of_occur_desc', 'ofns_desc', 'parks_nm', 'patrol_boro', 'pd_cd', 'pd_desc', 'prem_typ_desc', 'rpt_dt', 'station_name', 'susp_age_group', 'susp_race', 'susp_sex', 'transit_district', 'vic_age_group', 'vic_race', 'vic_sex', 'x_coord_cd', 'y_coord_cd', 'latitude', 'longitude', 'lat_lon', 'newgeoreferencedcolumn']

,cmplnt_num,addr_pct_cd,boro_nm,cmplnt_fr_dt,cmplnt_fr_tm,cmplnt_to_dt,cmplnt_to_tm,crm_atpt_cptd_cd,hadevelopt,housing_psa,...,transit_district,vic_age_group,vic_race,vic_sex,x_coord_cd,y_coord_cd,latitude,longitude,lat_lon,newgeoreferencedcolumn
0,298784667,114,QUEENS,12/09/2024,04:37:00,NaN,(null),COMPLETED,(null),NaN,...,NaN,UNKNOWN,UNKNOWN,E,1016307,227998,40.792430,-73.884228,"(40.79243, -73.884228)",POINT (-73.884228 40.79243)
1,308328240,41,BRONX,06/18/2025,16:00:00,NaN,(null),COMPLETED,(null),NaN,...,NaN,UNKNOWN,UNKNOWN,E,1017940,232184,40.803914,-73.878308,"(40.803914, -73.878308)",POINT (-73.878308 40.803914)
2,314788366,40,BRONX,10/17/2025,22:00:00,NaN,(null),COMPLETED,(null),NaN,...,NaN,18-24,BLACK HISPANIC,F,1005028,234516,40.810352,-73.924942,"(40.8103518634571, -73.924942325642)",POINT (-73.924942325642 40.8103518634571)
3,307568863,41,BRONX,03/24/2025,01:00:00,NaN,(null),COMPLETED,(null),NaN,...,NaN,18-24,WHITE,F,1013037,236657,40.816206,-73.896001,"(40.8162058439227, -73.8960011932583)",POINT (-73.8960011932583 40.8162058439227)
4,311408135H1,42,BRONX,08/18/2025,22:34:00,NaN,(null),COMPLETED,(null),NaN,...,NaN,25-44,BLACK,M,1009748,240283,40.826169,-73.907868,"(40.826169, -73.907868)",POINT (-73.907868 40.826169)

In [3]:
# Keep only useful columns
complaints = complaints[[
    'cmplnt_num',
    'boro_nm',
    'cmplnt_fr_dt',
    'law_cat_cd',
    'ofns_desc',
    'prem_typ_desc',
    'latitude',
    'longitude'
]]

print(complaints.shape)
complaints.head()

(186586, 8)

,cmplnt_num,boro_nm,cmplnt_fr_dt,law_cat_cd,ofns_desc,prem_typ_desc,latitude,longitude
0,298784667,QUEENS,12/09/2024,FELONY,ARSON,(null),40.792430,-73.884228
1,308328240,BRONX,06/18/2025,FELONY,ARSON,(null),40.803914,-73.878308
2,314788366,BRONX,10/17/2025,FELONY,RAPE,STREET,40.810352,-73.924942
3,307568863,BRONX,03/24/2025,FELONY,RAPE,OTHER,40.816206,-73.896001
4,311408135H1,BRONX,08/18/2025,FELONY,MURDER & NON-NEGL. MANSLAUGHTER,(null),40.826169,-73.907868

In [4]:
# Drop rows with missing coordinates
complaints = complaints.dropna(subset=['latitude', 'longitude'])

# Filter to relevant offense types (safety signals for nightlife venues)
relevant_offenses = [
    'ASSAULT 3 & RELATED OFFENSES',
    'FELONY ASSAULT',
    'ROBBERY',
    'PETIT LARCENY',
    'GRAND LARCENY',
    'HARRASSMENT 2',
    'CRIMINAL MISCHIEF & RELATED OF',
    'DANGEROUS DRUGS',
    'INTOXICATED & IMPAIRED DRIVING',
    'DISORDERLY CONDUCT',
    'ALCOHOLIC BEVERAGE CONTROL LAW',
    'OFFENSES AGAINST PUBLIC ADMINI',
    'SEX CRIMES',
]

complaints = complaints[complaints['ofns_desc'].isin(relevant_offenses)]

print(complaints.shape)
print(complaints['ofns_desc'].value_counts())

(117789, 8)
ofns_desc
GRAND LARCENY                     47537
FELONY ASSAULT                    29770
CRIMINAL MISCHIEF & RELATED OF    15634
ROBBERY                           15078
DANGEROUS DRUGS                    9114
SEX CRIMES                          656
Name: count, dtype: int64

In [5]:
complaints.to_csv('cleaned_complaints.csv', index=False)
print("Saved!")

Saved!

In [3]:
import pandas as pd

nta = pd.read_csv('2020_Neighborhood_Tabulation_Areas_(NTAs)_20260324.csv', low_memory=False)

# Normalize column names
nta.columns = nta.columns.str.lower().str.replace(' ', '')

print(nta.shape)
print(nta.columns.tolist())
nta.head()

(262, 12)
['borocode', 'boroname', 'countyfips', 'nta2020', 'ntaname', 'ntaabbrev', 'ntatype', 'cdta2020', 'cdtaname', 'shape_length', 'shape_area', 'the_geom']

,borocode,boroname,countyfips,nta2020,ntaname,ntaabbrev,ntatype,cdta2020,cdtaname,shape_length,shape_area,the_geom
0,3,Brooklyn,47,BK0101,Greenpoint,Grnpt,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),"28,919.5607283","35,321,808.4385",MULTIPOLYGON (((-73.9321339742769 40.728159603...
1,3,Brooklyn,47,BK0102,Williamsburg,Wllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),"28,134.0825628","28,852,852.9485",MULTIPOLYGON (((-73.95814292411644 40.72440428...
2,3,Brooklyn,47,BK0103,South Williamsburg,SWllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),"18,250.2800908","15,208,960.645",MULTIPOLYGON (((-73.95023693669857 40.70547324...
3,3,Brooklyn,47,BK0104,East Williamsburg,EWllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),"43,184.8003755","52,267,406.735",MULTIPOLYGON (((-73.92405909659959 40.71411155...
4,3,Brooklyn,47,BK0201,Brooklyn Heights,BkHts,0,BK02,BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...,"14,312.1924247","9,982,022.78507",MULTIPOLYGON (((-73.9923636691119 40.689690123...

In [4]:
# Keep only useful columns
nta = nta[[
    'boroname',
    'nta2020',
    'ntaname',
    'ntatype',
    'the_geom'
]]

# Drop any parks, cemeteries, airports (ntatype != 0 are non-residential areas)
nta = nta[nta['ntatype'] == 0]

print(nta.shape)
nta.head()

(197, 5)

,boroname,nta2020,ntaname,ntatype,the_geom
0,Brooklyn,BK0101,Greenpoint,0,MULTIPOLYGON (((-73.9321339742769 40.728159603...
1,Brooklyn,BK0102,Williamsburg,0,MULTIPOLYGON (((-73.95814292411644 40.72440428...
2,Brooklyn,BK0103,South Williamsburg,0,MULTIPOLYGON (((-73.95023693669857 40.70547324...
3,Brooklyn,BK0104,East Williamsburg,0,MULTIPOLYGON (((-73.92405909659959 40.71411155...
4,Brooklyn,BK0201,Brooklyn Heights,0,MULTIPOLYGON (((-73.9923636691119 40.689690123...

In [5]:
nta.to_csv('cleaned_nta.csv', index=False)
print("Saved!")

Saved!

In [31]:
# Aggregate venues by borough
venue_agg = venues.groupby('premisescounty').agg(
    venue_count=('licensepermitid', 'count'),
    avg_subway_entrances=('nearby_subway_entrances', 'mean'),
    avg_complaints=('nearby_complaints', 'mean')
).reset_index()

# Rename column for merging
venue_agg = venue_agg.rename(columns={'premisescounty': 'borough'})

print(venue_agg)

    borough  venue_count  avg_subway_entrances  avg_complaints
0     Bronx          599              4.398998      306.136895
1     Kings         2152              6.136617      194.509758
2  New York         5743             21.960299      634.007487
3    Queens         1928              4.010373      151.623444
4  Richmond          346              0.907514       38.855491

In [32]:
from sklearn.preprocessing import MinMaxScaler

# Higher subway = better, higher complaints = worse, higher venues = more competition
venue_agg['subway_score'] = (venue_agg['avg_subway_entrances'] / venue_agg['avg_subway_entrances'].max()) * 100
venue_agg['safety_score'] = (1 - venue_agg['avg_complaints'] / venue_agg['avg_complaints'].max()) * 100
venue_agg['competition_score'] = (1 - venue_agg['venue_count'] / venue_agg['venue_count'].max()) * 100

# Combine into final PopupIQ score (adjust weights as you like)
venue_agg['popupiq_score'] = (
    venue_agg['subway_score'] * 0.4 +
    venue_agg['safety_score'] * 0.4 +
    venue_agg['competition_score'] * 0.2
).round(1)

# Sort by score
venue_agg = venue_agg.sort_values('popupiq_score', ascending=False).reset_index(drop=True)

print(venue_agg[['borough', 'subway_score', 'safety_score', 'competition_score', 'popupiq_score']])

    borough  subway_score  safety_score  competition_score  popupiq_score
0  Richmond      4.132523     93.871446          93.975274           58.0
1     Kings     27.944141     69.320590          62.528295           51.4
2    Queens     18.261925     76.084913          66.428696           51.0
3     Bronx     20.031595     51.713994          89.569911           46.6
4  New York    100.000000      0.000000           0.000000           40.0

In [33]:
print(nta.columns.tolist())
print(nta.head())

['boroname', 'nta2020', 'ntaname', 'ntatype', 'the_geom']
   boroname nta2020             ntaname  ntatype  \
0  Brooklyn  BK0101          Greenpoint        0
1  Brooklyn  BK0102        Williamsburg        0
2  Brooklyn  BK0103  South Williamsburg        0
3  Brooklyn  BK0104   East Williamsburg        0
4  Brooklyn  BK0201    Brooklyn Heights        0

                                            the_geom
0  MULTIPOLYGON (((-73.9321339742769 40.728159603...
1  MULTIPOLYGON (((-73.95814292411644 40.72440428...
2  MULTIPOLYGON (((-73.95023693669857 40.70547324...
3  MULTIPOLYGON (((-73.92405909659959 40.71411155...
4  MULTIPOLYGON (((-73.9923636691119 40.689690123...

In [34]:
import re

# Extract the first coordinate pair from each MULTIPOLYGON as a centroid approximation
def extract_centroid(geom):
    coords = re.findall(r'(-?\d+\.\d+)\s(-?\d+\.\d+)', geom)
    if coords:
        lons = [float(c[0]) for c in coords]
        lats = [float(c[1]) for c in coords]
        return sum(lats)/len(lats), sum(lons)/len(lons)
    return None, None

nta['centroid_lat'], nta['centroid_lon'] = zip(*nta['the_geom'].apply(extract_centroid))

print(nta[['ntaname', 'centroid_lat', 'centroid_lon']].head(10))

                               ntaname  centroid_lat  centroid_lon
0                           Greenpoint     40.734549    -73.949064
1                         Williamsburg     40.715091    -73.962879
2                   South Williamsburg     40.703271    -73.955649
3                    East Williamsburg     40.715353    -73.930291
4                     Brooklyn Heights     40.696581    -73.994674
5  Downtown Brooklyn-DUMBO-Boerum Hill     40.697895    -73.986201
6                          Fort Greene     40.692808    -73.974930
7                         Clinton Hill     40.690714    -73.963626
8            Bedford-Stuyvesant (West)     40.689703    -73.950573
9            Bedford-Stuyvesant (East)     40.687719    -73.931821

In [36]:
# Check if we can extract coordinates from the_geom
print(nta['the_geom'].iloc[0][:100])

MULTIPOLYGON (((-73.9321339742769 40.72815960343333, -73.93238176169282 40.72799102790924, -73.93250

In [37]:
import re

def extract_bbox(geom):
    # Extract all numbers from the geometry string
    coords = re.findall(r'-?\d+\.\d+', geom)
    # Split into lons and lats (they alternate)
    lons = [float(coords[i]) for i in range(0, len(coords), 2)]
    lats = [float(coords[i]) for i in range(1, len(coords), 2)]
    return min(lons), max(lons), min(lats), max(lats)

# Apply to each neighborhood
nta[['min_lon', 'max_lon', 'min_lat', 'max_lat']] = nta['the_geom'].apply(
    lambda x: pd.Series(extract_bbox(x))
)

print(nta[['ntaname', 'min_lon', 'max_lon', 'min_lat', 'max_lat']].head())

              ntaname    min_lon    max_lon    min_lat    max_lat
0          Greenpoint -73.962341 -73.932134  40.718456  40.739128
1        Williamsburg -73.970069 -73.947213  40.705473  40.725321
2  South Williamsburg -73.968383 -73.941931  40.698039  40.708427
3   East Williamsburg -73.953485 -73.920749  40.700725  40.728160
4    Brooklyn Heights -74.001744 -73.988934  40.689137  40.703132

In [38]:
def assign_neighborhood(lat, lon):
    match = nta[
        (nta['min_lat'] <= lat) & (lat <= nta['max_lat']) &
        (nta['min_lon'] <= lon) & (lon <= nta['max_lon'])
    ]
    if len(match) > 0:
        return match.iloc[0]['ntaname']
    return None

# Apply to each venue (this may take a minute)
venues['neighborhood'] = venues.apply(
    lambda row: assign_neighborhood(row['latitude'], row['longitude']), axis=1
)

print(venues['neighborhood'].value_counts().head(10))
print("Unmatched venues:", venues['neighborhood'].isna().sum())

neighborhood
Midtown-Times Square                    729
Midtown South-Flatiron-Union Square     582
Chelsea-Hudson Yards                    569
Hell's Kitchen                          566
Financial District-Battery Park City    466
West Village                            304
SoHo-Little Italy-Hudson Square         295
East Village                            278
Greenwich Village                       241
Williamsburg                            228
Name: count, dtype: int64
Unmatched venues: 17

In [39]:
# Aggregate by neighborhood
neighborhood_scores = venues.groupby(['neighborhood', 'premisescounty']).agg(
    venue_count=('licensepermitid', 'count'),
    avg_subway_entrances=('nearby_subway_entrances', 'mean'),
    avg_complaints=('nearby_complaints', 'mean')
).reset_index()

# Build scores
neighborhood_scores['subway_score'] = (neighborhood_scores['avg_subway_entrances'] / neighborhood_scores['avg_subway_entrances'].max()) * 100
neighborhood_scores['safety_score'] = (1 - neighborhood_scores['avg_complaints'] / neighborhood_scores['avg_complaints'].max()) * 100
neighborhood_scores['competition_score'] = (1 - neighborhood_scores['venue_count'] / neighborhood_scores['venue_count'].max()) * 100

# Final PopupIQ score
neighborhood_scores['popupiq_score'] = (
    neighborhood_scores['subway_score'] * 0.4 +
    neighborhood_scores['safety_score'] * 0.4 +
    neighborhood_scores['competition_score'] * 0.2
).round(1)

# Sort by score
neighborhood_scores = neighborhood_scores.sort_values('popupiq_score', ascending=False).reset_index(drop=True)

print(neighborhood_scores[['neighborhood', 'premisescounty', 'venue_count', 'popupiq_score']].head(20))

                                         neighborhood premisescounty  \
0                Financial District-Battery Park City         Queens
1                                          Park Slope       New York
2                              Far Rockaway-Bayswater          Kings
3              Annadale-Huguenot-Prince's Bay-Woodrow       Richmond
4                     Rockaway Beach-Arverne-Edgemere         Queens
5              Sunset Park (East)-Borough Park (West)          Kings
6                                    South Ozone Park         Queens
7                                          Greenpoint       New York
8   Breezy Point-Belle Harbor-Rockaway Park-Broad ...          Kings
9                                        Borough Park          Kings
10                        Windsor Terrace-South Slope          Kings
11                               Oakwood-Richmondtown       Richmond
12                            Arden Heights-Rossville       Richmond
13             Springfield Gardens (South)-Brookville         Queens
14      New Springville-Willowbrook-Bulls Head-Travis       Richmond
15                                          Bellerose         Queens
16                            Great Kills-Eltingville       Richmond
17                                           Rosedale         Queens
18                          Throgs Neck-Schuylerville       New York
19                                         Auburndale       New York

    venue_count  popupiq_score
0             1           84.4
1             1           62.0
2             1           61.5
3             5           60.9
4            15           60.7
5             4           60.7
6            59           60.3
7             1           60.1
8             1           59.9
9             9           59.7
10           23           59.7
11            2           59.5
12            7           59.4
13           13           59.4
14           11           59.2
15            8           59.1
16           51           59.1
17            4           59.1
18            1           59.0
19            1           58.9

In [40]:
# Fix 1: Drop rows where borough doesn't match neighborhood's actual borough
borough_map = {
    'Bronx': 'Bronx',
    'Kings': 'Brooklyn',
    'New York': 'Manhattan',
    'Queens': 'Queens',
    'Richmond': 'Staten Island'
}

neighborhood_scores['boro_check'] = neighborhood_scores['premisescounty'].map(borough_map)

# Keep only rows where NTA borough matches
neighborhood_scores = neighborhood_scores.merge(
    nta[['ntaname', 'boroname']],
    left_on='neighborhood',
    right_on='ntaname'
)

neighborhood_scores = neighborhood_scores[
    neighborhood_scores['boroname'] == neighborhood_scores['boro_check']
]

# Fix 2: Only keep neighborhoods with at least 5 venues
neighborhood_scores = neighborhood_scores[neighborhood_scores['venue_count'] >= 5]

# Re-sort
neighborhood_scores = neighborhood_scores.sort_values('popupiq_score', ascending=False).reset_index(drop=True)

print(neighborhood_scores[['neighborhood', 'boroname', 'venue_count', 'popupiq_score']].head(20))

                                         neighborhood       boroname  \
0              Annadale-Huguenot-Prince's Bay-Woodrow  Staten Island
1                     Rockaway Beach-Arverne-Edgemere         Queens
2                                    South Ozone Park         Queens
3                                        Borough Park       Brooklyn
4                         Windsor Terrace-South Slope       Brooklyn
5                             Arden Heights-Rossville  Staten Island
6              Springfield Gardens (South)-Brookville         Queens
7       New Springville-Willowbrook-Bulls Head-Travis  Staten Island
8                                           Bellerose         Queens
9                             Great Kills-Eltingville  Staten Island
10  Breezy Point-Belle Harbor-Rockaway Park-Broad ...         Queens
11                Glen Oaks-Floral Park-New Hyde Park         Queens
12                              Bay Terrace-Clearview         Queens
13                                        Kew Gardens         Queens
14                     Rosebank-Shore Acres-Park Hill  Staten Island
15                            Mapleton-Midwood (West)       Brooklyn
16                             Douglaston-Little Neck         Queens
17                                   Gravesend (West)       Brooklyn
18                           Riverdale-Spuyten Duyvil          Bronx
19                             Tottenville-Charleston  Staten Island

    venue_count  popupiq_score
0             5           60.9
1            15           60.7
2            59           60.3
3             9           59.7
4            23           59.7
5             7           59.4
6            13           59.4
7            11           59.2
8             8           59.1
9            51           59.1
10           25           58.9
11           10           58.9
12           14           58.8
13            5           58.8
14            9           58.7
15           11           58.7
16           29           58.5
17           25           58.5
18           15           58.5
19           40           58.5

In [42]:
neighborhood_scores.to_csv('popupiq_scores.csv', index=False)
print("Saved!")

Saved!